### PR TITLE
Fix docker/adduser.sh

### PR DESCRIPTION
**Pull request by Supro**
Hi, this is "fix" for:

```bash
./adduser.sh some-user
cut: etc/ipsec.secrets: No such file or directory
```

Thank you for a such cool repo!

### CODE REVIEW

**Comment by jgimenez** [comment]
You definitely don't want to mess up with `/etc` in your machine. The `etc` directory is created when you run `start.sh`.

**Comment by Supro** [comment]
This refers to docker container. Dockerfile mounts `etc` directory `VOLUME ["/lib/modules", "/etc/ppp/chap-secrets", "/etc/ipsec.d/passwd", "/etc/ipsec.secrets"]` into the container. And then in `docker/adduser.sh` you're calling `SHARED_SECRET=$(cut -d'"' -f2 etc/ipsec.secrets)`, in `WORKDIR /opt/src` there's no `etc/ipsec.secrets`, it's located inside `/etc` directory in the container.

**Comment by Supro** [comment]
Just created another droplet to test it.

```bash
root@VPN:~/docker-ipsec-vpn-server# ./start.sh 
Unable to find image 'mobilejazz/docker-ipsec-vpn-server:latest' locally
latest: Pulling from mobilejazz/docker-ipsec-vpn-server
386a066cd84a: Pull complete 
3b66a58e8f20: Pull complete 
dc0f64cf55d3: Pull complete 
b1ffe4344789: Pull complete 
f819b6849cbe: Pull complete 
493d2ec6b456: Pull complete 
9347a7b30a44: Pull complete 
6333ae210599: Pull complete 
Digest: sha256:7819de3ddadc0170479d81ef17cd54969530d93dc7615eee7f1ad6c3c17340c9
Status: Downloaded newer image for mobilejazz/docker-ipsec-vpn-server:latest
4a3031a1d962030acb040d5f17c0023a527ed48af5703e599d8bd281a317f15f
```

```bash
root@VPN:~/docker-ipsec-vpn-server# ./adduser.sh roman-mac
cut: etc/ipsec.secrets: No such file or directory
Shared secret: 
Password for user is: rqJmscjBs5MneCv9uYS4
```

**Comment by jgimenez** [comment]
You're totally right, sorry. This is inside the docker.

**Pull request closed without merging**
