### PR TITLE
Upgraded Dockerfile and run to newest from hwdsl2

### PR DESCRIPTION
**Pull request by raunsbaekdk**
Upgraded Dockerfile and run to newest from hwdsl2

- All scripts now run from /opt/src/
- Upped Libreswan to 3.23
- Upped Debian to Stretch
- Check if sudo is available before running modprobe
- Added logs and shell easy commands

### CODE REVIEW

**Comment by jgimenez** [comment]
Thanks for your contribution. However I'm really unsure what this update does. There are many additions and deletions that probably belong to personal preference, such as directory changes or password generation changes. Thus, I can not merge it as is.

**Comment by raunsbaekdk** [comment]
Hi @jgimenez 

Updated files now matches @hwdsl2's repository.

The folder changes that you mention is the default folder that @hwdsl2 also uses: https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/Dockerfile#L39

Password generation changes are also from @hwdsl2's script: https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/run.sh#L57

I have documented how to use the .env file to change default DNS servers. Furthermore I have added two scripts that you can use to query logs and access shell: https://github.com/mobilejazz/docker-ipsec-vpn-server/pull/8/files#diff-194869a8d59739f4dd554796d22b7296 and https://github.com/mobilejazz/docker-ipsec-vpn-server/pull/8/files#diff-872026b9f3019b95b9423976f68b33c4

Your versions of @hwdsl2's scripts is very outdated, and that is why there are more changes than anticipated.

**Comment by lucasRolff** [comment]
This should get reopened 👍 The code looks good

**Comment by joe307bad** [comment]
It looks like there is stuff in here that would really be helpful. Specifically the custom DNS servers.

**Comment by raunsbaekdk** [comment]
Hi @joe307bad 

There sure was, however the author couldn't see that. So I created it my self:

https://github.com/raunsbaekdk/docker-ipsec-vpn-server
https://github.com/raunsbaekdk/docker-ipsec-vpn-server-tools

Steps:

1. ```docker pull raunsbaekdk/docker-ipsec-vpn-server```
2. ```git pull https://github.com/raunsbaekdk/docker-ipsec-vpn-server-tools```
3. ```cd docker-ipsec-vpn-server-tools```
4. ```chmod 755 *.sh```
5. ```./adduser.sh user```
6. ```echo "VPN_DNS_SRV1=8.8.8.8 VPN_DNS_SRV2=8.8.4.4" > etc/pre-up.sh```
7. ```./start.sh```

Remember to change to your own DNS servers.

You are more than welcome to contribute to my repo. Work needed:

1) READMEs
2) Move VPN credentials out from tools repo (right now they are saved into docker-ipsec-vpn-server-tools/etc)
3) Update run.sh (https://github.com/raunsbaekdk/docker-ipsec-vpn-server/blob/master/run.sh) to latest from: https://github.com/hwdsl2/docker-ipsec-vpn-server)

**Comment by joe307bad** [comment]
Thanks a lot @raunsbaekdk. Isn't there a way to do custom DNS via an `env` file like you described in your readme edits?

**Comment by raunsbaekdk** [comment]
@joe307bad Not at the moment, however you are welcome to add that feature. I haven't had the time to fix bugs (and fixed removed features).

**Comment by raunsbaekdk** [comment]
However mine uses Alpine and @hwdsl2 uses Debian.

Debian: 204 mb
Alpine Linux: 35 mb

**Comment by raunsbaekdk** [comment]
Also please @joe307bad that my version supports multiple users. That is why the structure of run.sh is a bit different.

**Comment by jgimenez** [comment]
I'm locking the conversation since it does not belong to this repo. As said in my previous comment, PRs are welcome, as long as changes are atomic and well documented, completely changing the code is not a contribution!

**Pull request closed without merging**
